language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
sudo: True
# command to run tests
script: nosetests
#
notifications:
  email:
    - david_gwartney@bmc.com
